homeWork 1
KaterinaKorobchits/KorobchitsAndroidPvt pull request #2
Opened 2019-06-16 14:05 UTC by KaterinaKorobchits

2019-06-17 18:37 UTC, tim-teacher requested changes
Оставил комменты ну и не совсем если честно понял логику как это все работает, сделайте мини описание пли :) - можно в описании к пул реквесту

2019-06-17 18:37 UTC, jushlwest commented on app/src/main/java/by/itacademy/korobchits/MainActivity.kt
> +
лишние строки

2019-06-17 18:37 UTC, jushlwest commented on app/src/main/java/by/itacademy/korobchits/dz1/Dz1Activity.kt
> +            setCountryName(R.id.austriaText, "AUSTRIA")
а почему нельзя в TextView прямо задать из стрингов?

2019-06-17 18:37 UTC, jushlwest commented on app/src/main/res/layout/dz1_activity.xml
> +            <LinearLayout android:layout_width="match_parent"
можно заменить на какой нить попроще тип, например View

2019-06-17 18:37 UTC, jushlwest commented on app/src/main/res/layout/dz1_activity.xml
> +            <LinearLayout android:layout_width="match_parent"
тоже самое LinearLayout тут не нужен

2019-06-17 18:37 UTC, jushlwest commented on app/src/main/res/layout/dz1_activity.xml
> +            <LinearLayout android:layout_width="match_parent"
тоже самое ну и дальше по xml

2019-06-17 19:46 UTC, KaterinaKorobchits commented on app/src/main/java/by/itacademy/korobchits/MainActivity.kt
> +
да, согласная я здесь, не заметила.

2019-06-17 19:51 UTC, KaterinaKorobchits commented on app/src/main/res/layout/dz1_activity.xml
> +            <LinearLayout android:layout_width="match_parent"
Что касается этого, отвечу легко)) -  я поняла, что задумка была нарисовать флаги с помощью ТОЛЬКО различных layoutов

2019-06-19 18:41 UTC, KaterinaKorobchits commented on app/src/main/java/by/itacademy/korobchits/dz1/Dz1Activity.kt
> +            setCountryName(R.id.austriaText, "AUSTRIA")
Тогда не подумала, что можно задать в прямо в Textview

2019-06-22 12:44 UTC, tim-teacher approved these changes

2019-06-22 13:15 UTC, AlexeyKasyanik approved these changes

2019-06-22 13:24 UTC, merged