dz5 ready
KaterinaKorobchits/KorobchitsAndroidPvt pull request #6
Opened 2019-06-26 11:53 UTC by KaterinaKorobchits

Получилось у меня через rotate все сделать - но это как-то мудрено)
![image](https://user-images.githubusercontent.com/46821793/60177660-1deea580-9822-11e9-9a71-622dd62a432d.png)

2019-06-29 08:57 UTC, tim-teacher requested changes

2019-06-29 08:57 UTC, jushlwest commented on app/src/main/java/by/itacademy/korobchits/dz5/Dz5ActivityOwl.kt
> +        (imageOwl.background as AnimationDrawable).start()
а остановка где?

2019-06-29 08:57 UTC, jushlwest commented on app/src/main/java/by/itacademy/korobchits/dz5/MyDiagramView.kt
> +    override fun onMeasure(widthMeasureSpec: Int, heightMeasureSpec: Int) {
я так понимаю это с классной работы осталось, если этот мето ничего не делает на самом деле то удалите его, ну и комменты поудаляйте там где AAA

2019-06-29 08:57 UTC, jushlwest commented on app/src/main/java/by/itacademy/korobchits/dz5/MyDiagramView.kt
> +    override fun onSizeChanged(w: Int, h: Int, oldw: Int, oldh: Int) {
опятьже зачем пустой метод

2019-06-29 08:57 UTC, jushlwest commented on app/src/main/java/by/itacademy/korobchits/dz5/MyDiagramView.kt
> +        invalidate()
invalidate() сам андроид вызывает после срабатывания метода onSizeChanged(), не нужно его еще раз вызывать, вы же по сути застявляете андроид рисовать View дважды

2019-06-29 08:57 UTC, jushlwest commented on app/src/main/java/by/itacademy/korobchits/dz5/MyDiagramView.kt
> +            canvas.drawCircle(centerX, (height / 2f - radius) / 1.5f, textHeight / 3f, pointPaint)
все расчеты должны быть вынесены в onSizeChanged()

2019-06-29 09:16 UTC, KaterinaKorobchits commented on app/src/main/java/by/itacademy/korobchits/dz5/MyDiagramView.kt
> +            canvas.drawCircle(centerX, (height / 2f - radius) / 1.5f, textHeight / 3f, pointPaint)
у меня расчеты могут происходить и без sizechanged, как я понимаю. поэтому все расчитывается сразу для onDraw

2019-06-29 09:18 UTC, KaterinaKorobchits commented on app/src/main/java/by/itacademy/korobchits/dz5/MyDiagramView.kt
> +    override fun onMeasure(widthMeasureSpec: Int, heightMeasureSpec: Int) {
я устанавливаю размеры определенные свои

2019-06-30 16:44 UTC, jushlwest commented on app/src/main/java/by/itacademy/korobchits/dz5/MyDiagramView.kt
> +            canvas.drawCircle(centerX, (height / 2f - radius) / 1.5f, textHeight / 3f, pointPaint)
ну поидее тогда нужно их в ините делать если нет зависимости от размеров

2019-06-30 16:45 UTC, tim-teacher approved these changes

2019-07-04 11:57 UTC, merged